services:
  - type: web
    name: my-blog-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn my_site.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString
      - key: DEBUG
        value: False
